### ISSUE TITLE
wind QC

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/glamod-marine-processing#20]
We want to implement a wind QC in level1e script.

#### Notes:
* northerlies given as 360°
* calm winds given as 0°

#### Flags:
* 0 m/s <= WS < 99.9 m/s
* 0° <= WD <= 360°
* WS == 0 & WD != 0
* WD == 0 & WS != 0

#### Questions @aanderss:
* how should we denote baffling wind
* ICOADS:  
  * calm winds given as 361°
  * baffling winds given as 362° 
  * should we adjust those values in ``cdm_reader_mapper``?
  * therefore, valid_min == 1°; valid_max == 362° in [mdf_reader.schema](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L157-L158)

#### Info:
* level1a: filter out values, which are not in the valid range
  * 0 m/s <= WS < 99.9 m/s
  * ⚠️ 1° <= WD <= 362°

**Comment by ludwiglierhammer** [comment]
Hi @sjnoone, we are trying to implement a wind QC in our marine processing tool. I hope you can help us with these questions:

* How do you differentiate between calm wind and baffling wind in your [glamod_land QC](https://github.com/glamod/glamod_landQC)? 
* What values do you set in your CDM observations-wd tables for these two wind "directions"? calm wind -> ``0.0``; bafflin wind -> ``99.0``?
* Do you know how the models interpret the data? 

I think we should both set the same values for both calm and baffling wind in our CDM tables.

**Comment by sjnoone** [comment]
Hi @ludwiglierhammer the best person to talk to about QC for wind is Robert Dunn @rjhd2 but he is on leave until early August.
best
Simon

**Comment by ludwiglierhammer** [comment]
@sjnoone: Thanks for your fast reply.

**Comment by ludwiglierhammer** [comment]
> Hi @sjnoone, we are trying to implement a wind QC in our marine processing tool. I hope you can help us with these questions:
> 
> * How do you differentiate between calm wind and baffling wind in your [glamod_land QC](https://github.com/glamod/glamod_landQC)?
> * What values do you set in your CDM observations-wd tables for these two wind "directions"? calm wind -> `0.0`; bafflin wind -> `99.0`?
> * Do you know how the models interpret the data?
> 
> I think we should both set the same values for both calm and baffling wind in our CDM tables.

Hi @rjhd2, could you please help us with these questions?

**Comment by ludwiglierhammer** [comment]
Hi @rjhd2, thanks for your reply.  

> Do you mean variable direction?

Yes, this is exactly what I meant. Sorry for the confusion.

**Comment by rjhd2** [comment]
For Variable wind (and also some Calm wind measurements), the subdaily data sometimes come with "V-Variable" or "C-Calm" comments in the `wind_direction_Measurement_Code` field. If these are present and the `wind_direction` measurement `999` then in my QC scripts I convert that to a `np.nan` which is then removed on writing back out to our final files.  Our system is that missing or flagged data are just not listed at all (empty data field) so this makes things consistent.  These flag comments are retained in the data files, so that users can see what was done.

One of the sets of wind QC checks is a set of logical arguments, so that directions are 1-360 for non-zero wind speeds, and 0N for calm winds etc.  But it is possible for a wind speed to exist without a direction (e.g. in the case of a "V-Variable" flag), though we don't do any specific QC on the observations with variable directions.  If there are conventions to follow, then I'm happy to do this - though would need to be careful with any choice of value to use.

I don't know how any models or reanalyses use the variable wind information, I'm afraid.

**Comment by ludwiglierhammer** [comment]
Thanks for your detailled reply, @rjhd2.

In our ICOADS data, wind direction of calm winds is given as ``361°`` and direction of variable winds as ``362°``.
Do you know this denotation in your input data? 

Just for my understanding (after your QC):

- calm winds: direction is ``0``; speed is ``0``
- variable winds: direction is ``np.nan``; speed is any value 

Is this right?

Our [wind QC](https://github.com/glamod/glamod-marine-processing/pull/22/files#diff-09b13d4f232ad076277aadae2a55f51bbcbf3091dbd70ad722e81ebba97c5888), which has not yet been implemented, flags the following:

- speed < ``0 m/s``
- speed > ``99.9 m/s`` (in our ICOADS data there are only 3 digits for wind speed)
- direction < ``0°``
- direction > ``360°``
- speed == ``0 m/s`` **and** direction != ``0°`` (calm winds)
- speed != ``0 m/s`` **and** direction == ``0°`` (variable winds; maybe we should set direction to ``np.nan`` in this cases tobe consistent with you, isn't it?)

Is this similar to your wind QC?

Sorry for all those questions. I just try to untie the knot in my head 😵

**Comment by rjhd2** [comment]
In order.
I've not come across that notation for calm and variable winds before.  Our QC flags directions `>360` (northerly winds). However, if this is a common way of presenting these two specific wind conditions, then it's something we could investigate to include in our QC.

If our wind speed`=0`, then direction should `=0`.  If no direction is given (no data or masked) then we could recover the direction if we presume the wind speed is correct.  If direction `!=0` is given then we flag that.

We don't try and do anything with a variable direction - this flag may be in another column from the input source, but in that case we just have a speed value and a missing value for the direction at the moment.

The subdaily land-QC script is [this one](https://github.com/glamod/glamod_landQC/blob/master/qc_tests/winds.py)  We follow a table of logical checks from Table 2 in [De Gaetano et al](https://journals.ametsoc.org/view/journals/atot/14/2/1520-0426_1997_014_0308_aqcrfh_2_0_co_2.xml).

So some of your checks are the same but there are some conventions within that paper that we follow (e.g., that calm winds `speed=0` have `direction=0`, but then northerly winds `speed >0` have `direction=360`).  The maximum speed is checked by our world records check (`113.2m/s`) - granted this is from a TC, but it's the value thats listed on the [WMO records  page](https://wmo.asu.edu/).

Any values which are removed (we've got an open ticket about the `direction=0/360` convention) are set to `np.nan`, but these are then removed from the datastream when we write out the final files.

Does some of that help?

**Comment by ludwiglierhammer** [comment]
Many thanks for your explanation. This will help us a lot.
I haven't seen this notation anywhere else either.

**Comment by ludwiglierhammer** [comment]
Your land QC looks quite similar to ours 👍

**Comment by ludwiglierhammer** [comment]
@aanderss: How should we deal with both wind directions ``361`` and ``362``?

**Comment by ludwiglierhammer** [comment]
Hi @rjhd2, I have a few more questions about your landQC workflow.

* Do you also map your input data to the [CDM](https://git.noc.ac.uk/brecinosrivas/cdm-mapper/-/blob/master/docs/cdm_latest.pdf) likewe do? I think so, but I am not entirely sure.
* If so, is your output format similar to [ours](https://github.com/glamod/cdm-testdata/tree/main/imma1_700/cdm_tables)?
* And could you please show me your input and output data?
* When exactly do you perform your QC in your workflow? We use it after mapping the input data to the CDM.

These questions are just for my understanding. Also, I am trying to make things similar/consistent since we are working in the same project. 

Thanks a lot!

**Comment by rjhd2** [comment]
We've got two stages of data formatting.  The first is converting to the standardised format (IFF) that we use for the subdaily from the individual sources.  Subsequent processing occurs to mingle stations together (MFF) and then QC them (QFF).  As the files are used by NOAA and C3S we then have a separate reformatting stage which converts only those elements to the CDM.  Unfortunately there's not a full link from the repo that does that reformatting (glamod_nuim) to the CDM definitions and tables (yet).

I will leave it to @sjnoone to confirm the similarity in the outputs of the CDM formatted in-situ sub-daily files as I'm not that familiar with them.  However from a glance, they do look similar, yes.

For the input and output data, do ping me an email and I can send an example file.  I've got plans to include tests in my QC repo in the next 6 months, so some example files will appear then, but there aren't any in the repo at the moment.

**Comment by rjhd2** [comment]
[Email with example input and output data sent]

**Comment by aanderss** [comment]
> @aanderss: How should we deal with both wind directions `361` and `362`?

Convert these ICOADS specific wind directions as stated in the [comment above ](https://github.com/glamod/glamod-marine-processing/issues/20#issuecomment-2288110394)
    361/calm winds: direction is 0; speed is 0
    362/variable winds: direction is np.nan; speed is any value

This conversion should be implemented in the initial format conversion with mdf reader/mapper,

**Comment by ludwiglierhammer** [comment]
Issue fixed in https://github.com/glamod/glamod-marine-processing/pull/22
